### ISSUE TITLE
Register and enroll user

### ISSUE THREAD

**Issue by ZhiqiangGuo1994** [IBM/blockchain-application-using-fabric-java-sdk#12]
I'm sorry to bother you. When I executed RegisterEnrollUser.java, user-****.ser file is generated.What‘s the effect of the generated new file?

**Comment by balajikadambi** [comment]
This file serializes the enrollment information. It is java serialized object.

**Comment by ZhiqiangGuo1994** [comment]
I want to execute the queryMarblesByOwner function in the marbles_chaincode.go file. How should I configure the current network?

**Comment by maheshwarishikha** [comment]
@ZhiqiangGuo1994 ,  If you want to deploy the different chaincode on the network then 
1. change chaincode related details in `blockchain-application-using-fabric-java-sdk/java/src/main/java/org/app/config/Config.java` 

2. Change chaincode invocation(invoke and query) functions in `blockchain-application-using-fabric-java-sdk/java/src/main/java/org/app/chaincode/invocation/`

Once done, build the client and execute APIs. It will work.

**Comment by ZhiqiangGuo1994** [comment]
I'm sorry to bother you. According this fabric network, I modified it into four organizations（org3,  org4）.But when I register a user with the new organization, I am prompted with the following error. Can you help me with it?

org.hyperledger.fabric_ca.sdk.exception.RegistrationException: Error while registering the user FabricTest.user.UserContext@ba54932 url: http://localhost:10054  POST request to http://localhost:10054/api/v1/register failed request body {"id":"user1541061530809","type":"user","max_enrollments":0,"affiliation":"org4","attrs":[]} with status code: 404. Response: {"result":"","errors":[{"code":63,"message":"Failed to get Affiliation: sql: no rows in result set"}
],"messages":[],"success":false} 
	at org.hyperledger.fabric_ca.sdk.HFCAClient.register(HFCAClient.java:236)
	at FabricTest.client.CAClient.registerUser(CAClient.java:125)
	at FabricTest.user.RegisterEnrollUser.main(RegisterEnrollUser.java:81)
Caused by: java.lang.Exception: POST request to http://localhost:10054/api/v1/register failed request body {"id":"user1541061530809","type":"user","max_enrollments":0,"affiliation":"org4","attrs":[]} with status code: 404. Response: {"result":"","errors":[{"code":63,"message":"Failed to get Affiliation: sql: no rows in result set"}
],"messages":[],"success":false}
	at org.hyperledger.fabric_ca.sdk.HFCAClient.httpPost(HFCAClient.java:609)
	at org.hyperledger.fabric_ca.sdk.HFCAClient.register(HFCAClient.java:227)
	... 2 more

**Comment by ZhiqiangGuo1994** [comment]
I want to add an endorsement policies to the code. What should I do?

**Comment by maheshwarishikha** [comment]
Hope the response helped and worked for you.
Closing this issue now.
