### ISSUE TITLE
endorsement policies

### ISSUE THREAD

**Issue by ZhiqiangGuo1994** [IBM/blockchain-application-using-fabric-java-sdk#13]
I'm sorry to bother you . I want to add an endorsement policies to the code. What should I do?

**Comment by ljbennett62** [comment]
@ZhiqiangGuo1994 - I want to make sure I understand - you want to add it to this code base? If so - open up a PR? Please clarify if that is not what you asking. tx

**Comment by ZhiqiangGuo1994** [comment]
> @ZhiqiangGuo1994 - I want to make sure I understand - you want to add it to this code base? If so - open up a PR? Please clarify if that is not what you asking. tx

Sorry, you may have misunderstood what I mean. At present, I am experimenting with this framework. I have encountered some problems in the process and would like to ask the author. I don't want to modify the entire framework.

**Comment by balajikadambi** [comment]
@ZhiqiangGuo1994 We have not tried the endorsement policies part here. You might need to refer to the test code here - https://github.com/hyperledger/fabric-sdk-java/blob/master/src/test/java/org/hyperledger/fabric/sdk/ChaincodeEndorsementPolicyTest.java.
