### ISSUE TITLE
How can I user couchDB

### ISSUE THREAD

**Issue by yanhuibin315** [IBM/blockchain-application-using-fabric-java-sdk#16]
I want to use couchDB, so how can I config it ??

**Comment by balajikadambi** [comment]
@yanhuibin315 we have not tried it here. you may need to refer to the documentation -https://hyperledger-fabric.readthedocs.io/en/release-1.3/couchdb_as_state_database.html.

**Comment by ZaheerUdDeen** [comment]
I want to contribute to this open source project. Can I take up this as my first challenge?

**Comment by ljbennett62** [comment]
@balajikadambi @yanhuibin315 - we always encourage other contributors - - submit a PR and we will review.

**Comment by ZaheerUdDeen** [comment]
Thanks! let me take up this challenge. Soon I will submit PR on this issue.
