### ISSUE TITLE
Unable to deploy a chain code with external dependency

### ISSUE THREAD

**Issue by anjalisn4** [IBM/blockchain-application-using-fabric-java-sdk#19]
If the chain code file has external dependency referring the go vendor directory,the chain code install fails.Any suggestions?

**Comment by maheshwarishikha** [comment]
@anjalisn4 , external dependancy has to be there and should be resolvable during chaincode install. If not, it will throw error.

You can share error, if you need more help for the same. I'll check and try to resolve. Thanks.

**Comment by anjalisn4** [comment]
I was able to resolve the dependency error using Go Vendoring management
