### ISSUE TITLE
Error when invoke chaincode

### ISSUE THREAD

**Issue by viettienbk** [IBM/blockchain-application-using-fabric-java-sdk#25]
Hi team,
I get error "java.lang.NullPointerException" when Invoke or query chaincode.
The output:
$ java -cp blockchain-client.jar org.app.chaincode.invocation.InvokeChaincode
`Mar 01, 2019 4:35:09 PM org.app.util.Util deleteDirectory
INFO: Deleting - admin.ser
Mar 01, 2019 4:35:09 PM org.app.util.Util deleteDirectory
INFO: Deleting - org1
Mar 01, 2019 4:35:09 PM org.app.util.Util deleteDirectory
INFO: Deleting - users
log4j:WARN No appenders could be found for logger (org.hyperledger.fabric.sdk.helper.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Mar 01, 2019 4:35:11 PM org.app.client.CAClient enrollAdminUser
INFO: CA -http://localhost:7054 Enrolled Admin.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Users/bapvn/blockchain-application-using-fabric-java-sdk/network_resources/blockchain-client.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Mar 01, 2019 4:35:12 PM org.app.client.ChannelClient sendTransactionProposal
INFO: Sending transaction proposal on channel mychannel
org.hyperledger.fabric.sdk.exception.InvalidArgumentException: java.lang.NullPointerException
        at org.hyperledger.fabric.sdk.ProposalResponse.getProposalResponsePayloadDeserializer(ProposalResponse.java:59)
        at org.hyperledger.fabric.sdk.ProposalResponse.getChaincodeActionResponsePayload(ProposalResponse.java:200)
        at org.app.client.ChannelClient.sendTransactionProposal(ChannelClient.java:121)
        at org.app.chaincode.invocation.InvokeChaincode.main(InvokeChaincode.java:88)
Caused by: java.lang.NullPointerException
        at org.hyperledger.fabric.sdk.ProposalResponse.getProposalResponsePayloadDeserializer(ProposalResponse.java:57)
        ... 3 more`

Im using java version "11.0.1" 2018-10-16 LTS, hyperledger fabric v1.1 and fabric-sdk-java v1.0.0
Please help me.

**Comment by viettienbk** [comment]
Sorry, my bad.

**Comment by lekya** [comment]
> Sorry, my bad.

Hey, Can you please tell me how did you solve that?
