### ISSUE TITLE
Wrong 'package name' convention: org.app.*

### ISSUE THREAD

**Issue by rafialhamd** [IBM/blockchain-application-using-fabric-java-sdk#26]
I see that below package name is used.

> package org.app.network;

The above package name to be used ONLY if the authors OWN the domain name `app.org`. Otherwise, please make use of something you all own OR org.example.* 

The idea behind package naming is that the **package name must be UNIQUE** universally.
If somebody owns `mycompany.com`, then then have the RIGHTS to make use of the package name `com.mycompany.*`. Otherwise, they should not.

Since, the internet domain name **hyperledger.org** has already been registered and OWNED by the Linux Foundation, they've the RIGHTS to make use of the domain name.

**Comment by balajikadambi** [comment]
@rafialhamd thanks for the information. As of now I see that the domain is not used anywhere. We will make the changes.

**Comment by rafialhamd** [comment]
Since, this is being hosted in **IBM repository**, it would be safer to make ues of something like, 
`package com.ibm.example.hyperledger.app.network`.

Thanks!

**Comment by balajikadambi** [comment]
@rafialhamd changed to org.example.
