### ISSUE TITLE
How do I modify the java source code and apply it?

### ISSUE THREAD

**Issue by kimjongmo** [IBM/blockchain-application-using-fabric-java-sdk#3]
After modifying the config.java file, I ran the java -cp blockchain-client.jar org.app.network.CreateChannel command. However, it says that it can not find or load the base class org.app.network.CreateChannel.

If I want to use the changed source, can you tell me what the process should be?

**Comment by balajikadambi** [comment]
@kimjongmo 
Please see if you chose the snapshot jar with dependencies under the target folder.
If you would like to contribute, please see the CONTRIBUTING.md file for more information.
If you would like to modify the source to experiment, please fork the repository.

Thanks,
Balaji

**Comment by balajikadambi** [comment]
@kimjongmo Please re-open the issue if you still have a problem running the code.
