### ISSUE TITLE
Deploy and Instantiate the chaincode when I run the command

### ISSUE THREAD

**Issue by FierceDog** [IBM/blockchain-application-using-fabric-java-sdk#32]
java -cp blockchain-client.jar org.app.network.DeployInstantiateChaincode

When I run this command I met this error  i can't solve:
 INFO: Chaincode fabcar on channel mychannel instantiation java.util.concurrent.CompletableFuture@8692d67[Completed exceptionally: org.hyperledger.fabric.sdk.exception.InvalidArgumentException: java.lang.NullPointerException]
Apr 28, 2019 1:22:06 AM org.app.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code instantiation FAILURE
Apr 28, 2019 1:22:06 AM org.app.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code instantiation FAILURE
Apr 28, 2019 1:22:06 AM org.app.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code instantiation FAILURE
Apr 28, 2019 1:22:06 AM org.app.network.DeployInstantiateChaincode main
INFO: fabcar- Chain code instantiation FAILURE

**Comment by maheshwarishikha** [comment]
@FierceDog , did you make any changes in code before executing?

**Comment by FierceDog** [comment]
Yes,I make changes in pom.xml. I added javax.xml.bind in the pom.xml

**Comment by maheshwarishikha** [comment]
@FierceDog , Sorry for delayed response...is the issue fixed now?

**Comment by FierceDog** [comment]
Sorry replyed so late，the issue fixed.&nbsp;


 
---Original---

**Comment by maheshwarishikha** [comment]
@FierceDog , it will be helpful if you can share about this more - how did it get fixed and what was the reason of this?
Thanks

**Comment by wangqinghuan** [comment]
I have same problem. How did you fix it? @FierceDog
