### ISSUE TITLE
Problem enrolling when using Identity Mixer

### ISSUE THREAD

**Issue by FrozenFort** [IBM/blockchain-application-using-fabric-java-sdk#34]
Hi guys~

Have you ever tried the feature Identity Mixer added in version 1.3.0? When I modified this example to use this feature, I get this error on the fabric-ca side:

`[ERROR] Failed to update level of user: No rows were affected when updating the state of identity`

Below is the place where I modified this example:
In the function org.example.client.CAClient#enrollAdminUser, I added the second line
```
103		Enrollment adminEnrollmentTmp = instance.enroll(username, password);
104		Enrollment adminEnrollment = instance.idemixEnroll(adminEnrollmentTmp, "Org1MSPidemix");
```

Do you have any suggestions? Thanks~

**Comment by maheshwarishikha** [comment]
@FrozenFort , Did it work for you?
We will not update this repository with Identity mixer feature...we might plan to do in a seperate repository with some use case. Hence closing this issue for now.

**Comment by gzuhlwang** [comment]
@FrozenFort hi, do you address the issue above? I am now doing  idemix things. If you made it, give me some hints, please. thanks.
