### ISSUE TITLE
Is there a way to attach a listener for new data inserted into the channel?

### ISSUE THREAD

**Issue by rampatra** [IBM/blockchain-application-using-fabric-java-sdk#40]
How do I attach a listener to detect new data being pushed to the channel by any other client? In the example, its clear how to setup orgs, peers, users, channel, and finally, post and query data, however, I am not clear as to how to invoke a particular method when new data is added to a channel.

**Comment by maheshwarishikha** [comment]
@rampatra 
How do I attach a listener to detect new data being pushed to the channel by any other client?  - if you want to get notified on each insertion by others - then you can try using events.

how to invoke a particular method when new data is added to a channel. - you have to write a query method to achieve this but when and how...you need to figure out.

**Comment by maheshwarishikha** [comment]
@rampatra , its long time....no updates here. So closing the issue, please feel free to reopen or open a new issue if required. Thanks.
