### ISSUE TITLE
but there is no dir chaincode and chaincode/input int the project

### ISSUE THREAD

**Issue by jiaxyan** [IBM/blockchain-application-using-fabric-java-sdk#5]
when run the deploychain, Encounter the peblem that it needs dir chaincode and chaincode/input, I found chaincode/src/github.com/fabcar somewhere else, but I do not know where to get chaincode/input...

**Comment by balajikadambi** [comment]
@jiaxyan we have not seen the error before. could you paste the entire error trace.

**Comment by jiaxyan** [comment]
@balajikadambi Thanks for you attention. Then I realize the reason is that I want to run the java code in eclipse immediately, I have'n move the chaincode(which is located in the dir'network_resources') to the java code path. (plus: this project is really a good tutorial for beginners)

**Comment by maheshwarishikha** [comment]
Good to know that it worked for you. Hence closing this issue. Thanks.
