### ISSUE TITLE
fabric 1.1 and 1.2 is not supported

### ISSUE THREAD

**Issue by linzhuvi** [IBM/blockchain-application-using-fabric-java-sdk#7]
hi:
thanks for the contribution of this java sdk demo, it is very helpfull.
unfortunately fabric 1.1.0 and 1.2.0 is not supported in this repo.
can you upgrade the code to 1.1.0 and 1.2.0? 
cause when i change the version of fabric-sdk-java from 1.0.0 to 1.1.0 or 1.2.0 
bad things happens like this:

![screenshot from 2018-08-29 16-06-24](https://user-images.githubusercontent.com/12165903/44774371-8b4f8c80-aba5-11e8-9e4e-590d8df3e0f9.png)

**Comment by maheshwarishikha** [comment]
@linzhuvi, Please check without changing fabric-sdk-java version. If you notice the repository  sets up the 1.1 fabric network and uses 1.0 fabric-sdk-java. So such operations (shown in code) works perfectly fine.

**Comment by linzhuvi** [comment]
@maheshwarishikha  , hi , that is what i am talking about, when can the project supoort the fabric-sdk-java 1.1/1.2 ? thanks.

**Comment by jamiecoleman92** [comment]
So mine is working fine with 1.1 but their is no image for x86 architecture on Dockerhub and when I try the one with no architecture tag it simply does not work. Should I be doing something different or should I wait for a new version of the image? I thought 1.3 was the latest but I may be wrong.

**Comment by keenkit** [comment]
I got the same issue `ECDSA KeyFactory not available` when running fabric `1.2.0` network, any one may help on this?

**Comment by krishna81m** [comment]
Any updates to 1.2? @maheshwarishikha

**Comment by maheshwarishikha** [comment]
@krishna81m  this repository talks about Fabric Java SDK but uses chaincode in 'golang'. It does not include Java chaincode.

**Comment by krishna81m** [comment]
> @krishna81m this repository talks about Fabric Java SDK but uses chaincode in 'golang'. It does not include Java chaincode.

My question was: why don't we have a Java chaincode example anywhere?

**Comment by maheshwarishikha** [comment]
@krishna81m , there were some limitations with Java chaincode and it was not fully supported with 1.1 and 1.2.
Java chaincode is going to be supported by Fabric 1.3 onwards.

**Comment by linzhuvi** [comment]
closed as no planned actions.
